"""One-shot (TICKET-053) : complète les clés manquantes des locales non-EN/FR.

N'ajoute QUE les clés absentes de chaque fichier `axiom/locales/<lang>.toml`
(préserve l'existant). Lancer depuis la racine du repo :
    .venv/bin/python maintenance/TICKET-053-i18n-rework/_fill_locales.py
"""
from __future__ import annotations
from pathlib import Path
import tomllib
import tomlkit

LOCALES = Path("axiom/locales")

# {key: {lang: value}}. Placeholders {..} et \n préservés. Style maison : « save »
# gardé comme emprunt dans les langues latines (comme le FR).
T: dict[str, dict[str, str]] = {
    "tab_setup": {"es": "Configuración de la historia", "de": "Story-Einrichtung", "it": "Impostazione storia", "pt": "Configuração da história", "ru": "Настройка истории", "zh": "故事设置", "ja": "ストーリー設定", "ko": "스토리 설정"},
    "export_save": {"es": "Exportar…", "de": "Exportieren…", "it": "Esporta…", "pt": "Exportar…", "ru": "Экспорт…", "zh": "导出…", "ja": "エクスポート…", "ko": "내보내기…"},
    "import_save": {"es": "Importar una save…", "de": "Spielstand importieren…", "it": "Importa un salvataggio…", "pt": "Importar um save…", "ru": "Импорт сохранения…", "zh": "导入存档…", "ja": "セーブをインポート…", "ko": "세이브 가져오기…"},
    "duplicate_save": {"es": "Duplicar", "de": "Duplizieren", "it": "Duplica", "pt": "Duplicar", "ru": "Дублировать", "zh": "复制", "ja": "複製", "ko": "복제"},
    "rename_save": {"es": "Renombrar", "de": "Umbenennen", "it": "Rinomina", "pt": "Renomear", "ru": "Переименовать", "zh": "重命名", "ja": "名前を変更", "ko": "이름 변경"},
    "edit_save": {"es": "Editar…", "de": "Bearbeiten…", "it": "Modifica…", "pt": "Editar…", "ru": "Изменить…", "zh": "编辑…", "ja": "編集…", "ko": "편집…"},
    "save_exported_msg": {"es": "Save exportada a:\n{path}", "de": "Spielstand exportiert nach:\n{path}", "it": "Salvataggio esportato in:\n{path}", "pt": "Save exportado para:\n{path}", "ru": "Сохранение экспортировано в:\n{path}", "zh": "存档已导出到：\n{path}", "ja": "セーブをエクスポートしました:\n{path}", "ko": "세이브를 내보냈습니다:\n{path}"},
    "save_imported_msg": {"es": "Save importada: {name}", "de": "Spielstand importiert: {name}", "it": "Salvataggio importato: {name}", "pt": "Save importado: {name}", "ru": "Сохранение импортировано: {name}", "zh": "存档已导入：{name}", "ja": "セーブをインポートしました: {name}", "ko": "세이브를 가져왔습니다: {name}"},
    "save_duplicated_msg": {"es": "Save duplicada: {name}", "de": "Spielstand dupliziert: {name}", "it": "Salvataggio duplicato: {name}", "pt": "Save duplicado: {name}", "ru": "Сохранение продублировано: {name}", "zh": "存档已复制：{name}", "ja": "セーブを複製しました: {name}", "ko": "세이브를 복제했습니다: {name}"},
    "save_edited_msg": {"es": "Corrección aplicada (turno {turn}).", "de": "Korrektur angewendet (Zug {turn}).", "it": "Correzione applicata (turno {turn}).", "pt": "Correção aplicada (turno {turn}).", "ru": "Исправление применено (ход {turn}).", "zh": "已应用修正（回合 {turn}）。", "ja": "修正を適用しました（ターン {turn}）。", "ko": "수정이 적용되었습니다 (턴 {turn})."},
    "save_edit_nochange_msg": {"es": "No hay cambios que aplicar.", "de": "Keine Änderung anzuwenden.", "it": "Nessuna modifica da applicare.", "pt": "Nenhuma alteração a aplicar.", "ru": "Нет изменений для применения.", "zh": "没有可应用的更改。", "ja": "適用する変更はありません。", "ko": "적용할 변경 사항이 없습니다."},
    "save_import_force_q": {"es": "Esta save proviene de otro universo. ¿Importarla de todos modos?", "de": "Dieser Spielstand stammt aus einem anderen Universum. Trotzdem importieren?", "it": "Questo salvataggio proviene da un altro universo. Importarlo comunque?", "pt": "Este save vem de outro universo. Importar mesmo assim?", "ru": "Это сохранение из другой вселенной. Всё равно импортировать?", "zh": "此存档来自另一个宇宙。仍要导入吗？", "ja": "このセーブは別のユニバースのものです。それでもインポートしますか？", "ko": "이 세이브는 다른 유니버스의 것입니다. 그래도 가져올까요?"},
    "edit_save_title": {"es": "Editar el estado de la save", "de": "Spielstand bearbeiten", "it": "Modifica lo stato del salvataggio", "pt": "Editar o estado do save", "ru": "Изменить состояние сохранения", "zh": "编辑存档状态", "ja": "セーブ状態を編集", "ko": "세이브 상태 편집"},
    "edit_save_hint": {
        "es": "Modifica los valores siguientes y confirma: solo se aplican las diferencias, como correcciones trazables (el rebobinado se conserva).\n[save] y [point] son informativos; eliminar una línea [[inventory]] quita el objeto; solo se añaden las NUEVAS entradas [[modifiers]].",
        "de": "Ändere die Werte unten und bestätige: Nur die Unterschiede werden als nachvollziehbare Korrekturen angewendet (das Zurückspulen bleibt erhalten).\n[save] und [point] sind informativ; das Entfernen einer [[inventory]]-Zeile entfernt den Gegenstand; nur NEUE [[modifiers]]-Einträge werden hinzugefügt.",
        "it": "Modifica i valori sottostanti e conferma: vengono applicate solo le differenze, come correzioni tracciabili (il riavvolgimento è preservato).\n[save] e [point] sono informativi; rimuovere una riga [[inventory]] rimuove l'oggetto; vengono aggiunte solo le NUOVE voci [[modifiers]].",
        "pt": "Edite os valores abaixo e confirme: apenas as diferenças são aplicadas, como correções rastreáveis (o retrocesso é preservado).\n[save] e [point] são informativos; remover uma linha [[inventory]] remove o item; apenas as NOVAS entradas [[modifiers]] são adicionadas.",
        "ru": "Измените значения ниже и подтвердите: применяются только различия, как отслеживаемые исправления (перемотка сохраняется).\n[save] и [point] информативны; удаление строки [[inventory]] убирает предмет; добавляются только НОВЫЕ записи [[modifiers]].",
        "zh": "修改下面的值后确认：仅应用差异，作为可追溯的修正（回溯保留）。\n[save] 和 [point] 仅供参考；删除某行 [[inventory]] 会移除该物品；只会添加新的 [[modifiers]] 条目。",
        "ja": "下の値を編集して確定してください：差分のみが追跡可能な修正として適用されます（巻き戻しは保持されます）。\n[save] と [point] は参考情報です。[[inventory]] 行を削除するとそのアイテムが除去されます。追加されるのは新規の [[modifiers]] エントリのみです。",
        "ko": "아래 값을 편집한 후 확인하세요: 차이점만 추적 가능한 수정으로 적용됩니다(되감기는 유지됨).\n[save]와 [point]는 참고용입니다. [[inventory]] 줄을 삭제하면 해당 아이템이 제거됩니다. 새로운 [[modifiers]] 항목만 추가됩니다.",
    },
    "duplicate_save_name_q": {"es": "Nombre de la save duplicada:", "de": "Name des duplizierten Spielstands:", "it": "Nome del salvataggio duplicato:", "pt": "Nome do save duplicado:", "ru": "Имя продублированного сохранения:", "zh": "复制存档的名称：", "ja": "複製したセーブの名前:", "ko": "복제한 세이브의 이름:"},
    "continuous_save_note": {"es": "El guardado es continuo: cada turno se registra al instante — «Duplicar» crea un punto de ramificación.", "de": "Das Speichern erfolgt fortlaufend: Jeder Zug wird sofort aufgezeichnet — „Duplizieren“ erstellt einen Verzweigungspunkt.", "it": "Il salvataggio è continuo: ogni turno viene registrato immediatamente — «Duplica» crea un punto di diramazione.", "pt": "O salvamento é contínuo: cada turno é registrado imediatamente — \"Duplicar\" cria um ponto de ramificação.", "ru": "Сохранение непрерывное: каждый ход записывается сразу — «Дублировать» создаёт точку ветвления.", "zh": "保存是连续的：每个回合都会立即记录——“复制”会创建一个分支点。", "ja": "セーブは継続的です：各ターンが即座に記録されます — 「複製」で分岐点を作成します。", "ko": "저장은 연속적입니다: 매 턴이 즉시 기록됩니다 — \"복제\"는 분기점을 만듭니다."},
    "tab_files": {"es": "Archivos", "de": "Dateien", "it": "File", "pt": "Arquivos", "ru": "Файлы", "zh": "文件", "ja": "ファイル", "ko": "파일"},
    "files_save_file": {"es": "Guardar el archivo", "de": "Datei speichern", "it": "Salva il file", "pt": "Salvar o arquivo", "ru": "Сохранить файл", "zh": "保存文件", "ja": "ファイルを保存", "ko": "파일 저장"},
    "files_flat_db_msg": {
        "es": "Este universo es un archivo .db plano: no tiene archivos de texto fuente.\nConviértelo en un universo-carpeta (archivos TOML/MD + caché compilada) para editarlo como texto.\nLas saves existentes se conservan; el .db original se guarda como archivo .bak.",
        "de": "Dieses Universum ist eine flache .db-Datei: Es hat keine Quelltextdateien.\nWandle es in ein Ordner-Universum um (TOML/MD-Dateien + kompilierter Cache), um es als Text zu bearbeiten.\nVorhandene Spielstände bleiben erhalten; die ursprüngliche .db wird als .bak-Datei aufbewahrt.",
        "it": "Questo universo è un file .db piatto: non ha file di testo sorgente.\nConvertilo in un universo-cartella (file TOML/MD + cache compilata) per modificarlo come testo.\nI salvataggi esistenti vengono conservati; il .db originale è mantenuto come file .bak.",
        "pt": "Este universo é um arquivo .db plano: não tem arquivos de texto-fonte.\nConverta-o em um universo-pasta (arquivos TOML/MD + cache compilado) para editá-lo como texto.\nOs saves existentes são mantidos; o .db original é preservado como arquivo .bak.",
        "ru": "Эта вселенная — плоский файл .db: у неё нет исходных текстовых файлов.\nПреобразуйте её во вселенную-папку (файлы TOML/MD + скомпилированный кэш), чтобы редактировать как текст.\nСуществующие сохранения сохраняются; исходный .db остаётся в виде файла .bak.",
        "zh": "此宇宙是一个扁平的 .db 文件：没有源文本文件。\n将其转换为文件夹宇宙（TOML/MD 文件 + 编译缓存）即可作为文本编辑。\n现有存档会保留；原始 .db 会保存为 .bak 文件。",
        "ja": "このユニバースはフラットな .db ファイルです：ソーステキストファイルがありません。\nテキストとして編集するには、フォルダ・ユニバース（TOML/MD ファイル + コンパイル済みキャッシュ）に変換してください。\n既存のセーブは保持されます。元の .db は .bak ファイルとして保存されます。",
        "ko": "이 유니버스는 평면 .db 파일입니다: 소스 텍스트 파일이 없습니다.\n텍스트로 편집하려면 폴더 유니버스(TOML/MD 파일 + 컴파일된 캐시)로 변환하세요.\n기존 세이브는 유지됩니다. 원본 .db는 .bak 파일로 보존됩니다.",
    },
    "files_convert_btn": {"es": "Convertir en universo-carpeta", "de": "In Ordner-Universum umwandeln", "it": "Converti in universo-cartella", "pt": "Converter em universo-pasta", "ru": "Преобразовать во вселенную-папку", "zh": "转换为文件夹宇宙", "ja": "フォルダ・ユニバースに変換", "ko": "폴더 유니버스로 변환"},
    "files_convert_confirm": {"es": "¿Convertir este universo en una carpeta fuente? Las saves existentes se mueven a archivos separados y el .db original se guarda como .bak.", "de": "Dieses Universum in einen Quellordner umwandeln? Vorhandene Spielstände werden in separate Dateien verschoben und die ursprüngliche .db wird als .bak aufbewahrt.", "it": "Convertire questo universo in una cartella sorgente? I salvataggi esistenti vengono spostati in file separati e il .db originale è mantenuto come .bak.", "pt": "Converter este universo em uma pasta-fonte? Os saves existentes são movidos para arquivos separados e o .db original é preservado como .bak.", "ru": "Преобразовать эту вселенную в папку-источник? Существующие сохранения переносятся в отдельные файлы, а исходный .db остаётся как .bak.", "zh": "将此宇宙转换为源文件夹？现有存档会移至单独的文件，原始 .db 会保存为 .bak。", "ja": "このユニバースをソースフォルダに変換しますか？既存のセーブは別ファイルに移され、元の .db は .bak として保持されます。", "ko": "이 유니버스를 소스 폴더로 변환할까요? 기존 세이브는 별도 파일로 이동되고 원본 .db는 .bak로 보존됩니다."},
    "files_converted_msg": {"es": "Universo convertido en una carpeta fuente.", "de": "Universum in einen Quellordner umgewandelt.", "it": "Universo convertito in una cartella sorgente.", "pt": "Universo convertido em uma pasta-fonte.", "ru": "Вселенная преобразована в папку-источник.", "zh": "宇宙已转换为源文件夹。", "ja": "ユニバースをソースフォルダに変換しました。", "ko": "유니버스를 소스 폴더로 변환했습니다."},
    "files_saved_refreshed": {"es": "Archivo fuente guardado — definición del universo recargada.", "de": "Quelldatei gespeichert — Universumsdefinition neu geladen.", "it": "File sorgente salvato — definizione dell'universo ricaricata.", "pt": "Arquivo-fonte salvo — definição do universo recarregada.", "ru": "Исходный файл сохранён — определение вселенной перезагружено.", "zh": "源文件已保存——已重新加载宇宙定义。", "ja": "ソースファイルを保存しました — ユニバース定義を再読み込みしました。", "ko": "소스 파일을 저장했습니다 — 유니버스 정의를 다시 불러왔습니다."},
    "files_unsaved_q": {"es": "¿Guardar los cambios de {name}? (No los descarta)", "de": "Änderungen an {name} speichern? (Nein verwirft sie)", "it": "Salvare le modifiche a {name}? (No le annulla)", "pt": "Salvar as alterações de {name}? (Não as descarta)", "ru": "Сохранить изменения в {name}? (Нет — отменить их)", "zh": "保存对 {name} 的更改吗？（否将放弃更改）", "ja": "{name} の変更を保存しますか？（いいえ で破棄）", "ko": "{name}의 변경 사항을 저장할까요? (아니요 = 취소)"},
    "uac_folder_required": {"es": "Esto requiere un universo-carpeta (fuente de texto). Convierte el .db plano desde la pestaña «Archivos» del Creator Studio.", "de": "Dies erfordert ein Ordner-Universum (Textquelle). Wandle die flache .db im Reiter „Dateien“ des Creator Studio um.", "it": "Questo richiede un universo-cartella (sorgente di testo). Converti il .db piatto dalla scheda «File» del Creator Studio.", "pt": "Isto requer um universo-pasta (fonte de texto). Converta o .db plano na aba \"Arquivos\" do Creator Studio.", "ru": "Для этого нужна вселенная-папка (текстовый источник). Преобразуйте плоский .db во вкладке «Файлы» Creator Studio.", "zh": "这需要文件夹宇宙（文本源）。请在 Creator Studio 的“文件”选项卡中转换扁平 .db。", "ja": "これにはフォルダ・ユニバース（テキストソース）が必要です。Creator Studio の「ファイル」タブでフラットな .db を変換してください。", "ko": "이 기능에는 폴더 유니버스(텍스트 소스)가 필요합니다. Creator Studio의 \"파일\" 탭에서 평면 .db를 변환하세요."},
    "populate_preview_check": {"es": "Previsualizar el diff de texto antes de aplicar (universo-carpeta)", "de": "Text-Diff vor dem Anwenden anzeigen (Ordner-Universum)", "it": "Anteprima del diff di testo prima di applicare (universo-cartella)", "pt": "Pré-visualizar o diff de texto antes de aplicar (universo-pasta)", "ru": "Предпросмотр текстового diff перед применением (вселенная-папка)", "zh": "应用前预览文本差异（文件夹宇宙）", "ja": "適用前にテキスト差分をプレビュー（フォルダ・ユニバース）", "ko": "적용 전 텍스트 diff 미리보기 (폴더 유니버스)"},
    "preview_no_changes": {"es": "La generación no produjo contenido nuevo.", "de": "Die Generierung hat keinen neuen Inhalt erzeugt.", "it": "La generazione non ha prodotto nuovi contenuti.", "pt": "A geração não produziu nenhum conteúdo novo.", "ru": "Генерация не дала нового содержимого.", "zh": "本次生成没有产生新内容。", "ja": "生成によって新しいコンテンツは作成されませんでした。", "ko": "생성으로 새로운 콘텐츠가 만들어지지 않았습니다."},
    "diff_preview_title": {"es": "Previsualización de los cambios del universo", "de": "Vorschau der Universumsänderungen", "it": "Anteprima delle modifiche all'universo", "pt": "Pré-visualização das alterações do universo", "ru": "Предпросмотр изменений вселенной", "zh": "宇宙更改预览", "ja": "ユニバース変更のプレビュー", "ko": "유니버스 변경 미리보기"},
    "diff_preview_hint": {"es": "{count} archivo(s) fuente afectado(s). Revisa y luego aplica o cancela — no se escribe nada hasta que apliques.", "de": "{count} Quelldatei(en) betroffen. Überprüfe, dann anwenden oder abbrechen — bis zum Anwenden wird nichts geschrieben.", "it": "{count} file sorgente interessati. Controlla, poi applica o annulla — nulla viene scritto finché non applichi.", "pt": "{count} arquivo(s)-fonte afetado(s). Revise e depois aplique ou cancele — nada é gravado até você aplicar.", "ru": "Затронуто исходных файлов: {count}. Просмотрите, затем примените или отмените — ничего не записывается до применения.", "zh": "受影响的源文件：{count} 个。请检查后应用或取消——应用前不会写入任何内容。", "ja": "影響を受けるソースファイル: {count} 件。確認してから適用またはキャンセルしてください — 適用するまで何も書き込まれません。", "ko": "영향을 받는 소스 파일 {count}개. 검토 후 적용하거나 취소하세요 — 적용하기 전에는 아무것도 기록되지 않습니다."},
    "apply_changes_btn": {"es": "Aplicar", "de": "Anwenden", "it": "Applica", "pt": "Aplicar", "ru": "Применить", "zh": "应用", "ja": "適用", "ko": "적용"},
    "staged_applied_msg": {"es": "Cambios aplicados a la fuente del universo.", "de": "Änderungen auf die Universumsquelle angewendet.", "it": "Modifiche applicate alla sorgente dell'universo.", "pt": "Alterações aplicadas à fonte do universo.", "ru": "Изменения применены к источнику вселенной.", "zh": "更改已应用到宇宙源。", "ja": "ユニバースのソースに変更を適用しました。", "ko": "유니버스 소스에 변경 사항을 적용했습니다."},
    "canon_auto": {"es": "Canon automático", "de": "Auto-Kanon", "it": "Canone automatico", "pt": "Cânone automático", "ru": "Авто-канон", "zh": "自动正典", "ja": "自動カノン", "ko": "자동 정사"},
    "canon_auto_tooltip": {"es": "Tras cada turno, añade en silencio lo que la historia ha establecido (personajes, lugares, hechos) a la definición del universo. Desactivado por defecto.", "de": "Fügt nach jedem Zug stillschweigend das von der Geschichte Etablierte (Figuren, Orte, Fakten) zur Universumsdefinition hinzu. Standardmäßig aus.", "it": "Dopo ogni turno, aggiunge silenziosamente ciò che la storia ha stabilito (personaggi, luoghi, fatti) alla definizione dell'universo. Disattivato per impostazione predefinita.", "pt": "Após cada turno, adiciona silenciosamente o que a história estabeleceu (personagens, lugares, fatos) à definição do universo. Desativado por padrão.", "ru": "После каждого хода молча добавляет установленное историей (персонажи, места, факты) в определение вселенной. По умолчанию выключено.", "zh": "每回合后，自动将故事确立的内容（角色、地点、事实）静默添加到宇宙定义中。默认关闭。", "ja": "毎ターン後、物語が確立した内容（キャラクター、場所、事実）を静かにユニバース定義へ追加します。既定ではオフ。", "ko": "매 턴 후, 이야기가 확립한 내용(캐릭터, 장소, 사실)을 조용히 유니버스 정의에 추가합니다. 기본값은 꺼짐."},
    "canonize_btn": {"es": "Canonizar…", "de": "Kanonisieren…", "it": "Canonizza…", "pt": "Canonizar…", "ru": "Канонизировать…", "zh": "正典化…", "ja": "カノン化…", "ko": "정사화…"},
    "canonize_tooltip": {"es": "Extrae lo que la historia reciente ha establecido y lo añade a la definición del universo (con previsualización de los cambios de texto).", "de": "Extrahiert das von der jüngsten Geschichte Etablierte und fügt es zur Universumsdefinition hinzu (mit Vorschau der Textänderungen).", "it": "Estrae ciò che la storia recente ha stabilito e lo aggiunge alla definizione dell'universo (con anteprima delle modifiche di testo).", "pt": "Extrai o que a história recente estabeleceu e o adiciona à definição do universo (com pré-visualização das alterações de texto).", "ru": "Извлекает установленное недавней историей и добавляет в определение вселенной (с предпросмотром текстовых изменений).", "zh": "提取近期故事所确立的内容并添加到宇宙定义中（附带文本更改预览）。", "ja": "最近の物語が確立した内容を抽出し、ユニバース定義に追加します（テキスト変更のプレビュー付き）。", "ko": "최근 이야기가 확립한 내용을 추출하여 유니버스 정의에 추가합니다(텍스트 변경 미리보기 포함)."},
    "canonize_running": {"es": "Canonizando la historia reciente…", "de": "Jüngste Geschichte wird kanonisiert…", "it": "Canonizzazione della storia recente…", "pt": "Canonizando a história recente…", "ru": "Канонизация недавней истории…", "zh": "正在正典化近期故事…", "ja": "最近の物語をカノン化中…", "ko": "최근 이야기를 정사화하는 중…"},
    "canon_none_msg": {"es": "Nada nuevo que canonizar.", "de": "Nichts Neues zu kanonisieren.", "it": "Niente di nuovo da canonizzare.", "pt": "Nada de novo para canonizar.", "ru": "Нет ничего нового для канонизации.", "zh": "没有可正典化的新内容。", "ja": "カノン化する新しい内容はありません。", "ko": "정사화할 새로운 내용이 없습니다."},
    "canon_applied_msg": {"es": "Canon del universo actualizado.", "de": "Universumskanon aktualisiert.", "it": "Canone dell'universo aggiornato.", "pt": "Cânone do universo atualizado.", "ru": "Канон вселенной обновлён.", "zh": "宇宙正典已更新。", "ja": "ユニバースのカノンを更新しました。", "ko": "유니버스 정사를 업데이트했습니다."},
    "canon_counts": {"es": "({entities} entidades, {lore} entradas de lore)", "de": "({entities} Entitäten, {lore} Lore-Einträge)", "it": "({entities} entità, {lore} voci di lore)", "pt": "({entities} entidades, {lore} entradas de lore)", "ru": "({entities} сущностей, {lore} записей лора)", "zh": "（{entities} 个实体，{lore} 条设定）", "ja": "（エンティティ {entities} 件、ロア {lore} 件）", "ko": "(엔티티 {entities}개, 설정 {lore}개)"},
    "gemini_fallback_label": {"es": "Modelo de respaldo (cuota):", "de": "Fallback-Modell (Kontingent):", "it": "Modello di riserva (quota):", "pt": "Modelo de reserva (cota):", "ru": "Резервная модель (квота):", "zh": "备用模型（配额）：", "ja": "フォールバックモデル（クォータ）：", "ko": "대체 모델 (할당량):"},
    "gemini_fallback_tooltip": {"es": "Modelo usado cuando el modelo principal sigue limitado (429) tras los reintentos automáticos. Las cuotas de Google son por modelo: otro modelo suele tener aún presupuesto. Vacío = ninguno.", "de": "Modell, das verwendet wird, wenn das Hauptmodell nach automatischen Wiederholungen weiterhin gedrosselt ist (429). Google-Kontingente gelten pro Modell: ein anderes Modell hat meist noch Budget. Leer = keines.", "it": "Modello usato quando il modello principale è ancora limitato (429) dopo i tentativi automatici. Le quote di Google sono per modello: un altro modello di solito ha ancora budget. Vuoto = nessuno.", "pt": "Modelo usado quando o modelo principal continua limitado (429) após as tentativas automáticas. As cotas do Google são por modelo: outro modelo geralmente ainda tem orçamento. Vazio = nenhum.", "ru": "Модель, используемая, когда основная модель всё ещё ограничена (429) после автоматических повторов. Квоты Google действуют на каждую модель: у другой модели обычно ещё есть бюджет. Пусто = нет.", "zh": "当主模型在自动重试后仍被限流（429）时使用的模型。Google 配额按模型计算：另一个模型通常仍有额度。留空 = 无。", "ja": "自動リトライ後もメインモデルが制限（429）されている場合に使用するモデル。Google のクォータはモデルごとなので、別モデルなら通常まだ余裕があります。空 = なし。", "ko": "자동 재시도 후에도 기본 모델이 계속 제한(429)될 때 사용하는 모델입니다. Google 할당량은 모델별이므로 다른 모델은 보통 여유가 있습니다. 비우면 없음."},
    "llm_rpm_label": {"es": "Solicitudes máx. / minuto:", "de": "Max. Anfragen / Minute:", "it": "Richieste max / minuto:", "pt": "Solicitações máx. / minuto:", "ru": "Макс. запросов / минуту:", "zh": "每分钟最大请求数：", "ja": "最大リクエスト数 / 分：", "ko": "분당 최대 요청 수:"},
    "llm_rpm_tooltip": {"es": "Ralentiza las llamadas al LLM para respetar la cuota de tu plan (p. ej. free tier: 10/min por modelo — pon 9). 0 = ilimitado.", "de": "Verlangsamt LLM-Aufrufe, um das Kontingent deines Tarifs einzuhalten (z. B. Free Tier: 10/min pro Modell — auf 9 setzen). 0 = unbegrenzt.", "it": "Rallenta le chiamate all'LLM per rispettare la quota del tuo piano (es. free tier: 10/min per modello — imposta 9). 0 = illimitato.", "pt": "Reduz a velocidade das chamadas ao LLM para respeitar a cota do seu plano (ex. free tier: 10/min por modelo — defina 9). 0 = ilimitado.", "ru": "Замедляет вызовы LLM, чтобы соблюдать квоту вашего тарифа (например, free tier: 10/мин на модель — поставьте 9). 0 = без ограничений.", "zh": "降低 LLM 调用速度以遵守你套餐的配额（例如免费层：每个模型 10/分钟——设为 9）。0 = 无限制。", "ja": "プランのクォータを守るために LLM 呼び出しを遅くします（例：無料枠はモデルごとに 10/分 — 9 に設定）。0 = 無制限。", "ko": "요금제 할당량을 지키도록 LLM 호출 속도를 늦춥니다(예: 무료 등급은 모델당 10/분 — 9로 설정). 0 = 무제한."},
    "rpm_unlimited": {"es": "Ilimitado", "de": "Unbegrenzt", "it": "Illimitato", "pt": "Ilimitado", "ru": "Без ограничений", "zh": "无限制", "ja": "無制限", "ko": "무제한"},
    "cancel_generation": {"es": "✖ Cancelar la generación", "de": "✖ Generierung abbrechen", "it": "✖ Annulla la generazione", "pt": "✖ Cancelar a geração", "ru": "✖ Отменить генерацию", "zh": "✖ 取消生成", "ja": "✖ 生成をキャンセル", "ko": "✖ 생성 취소"},
    "generation_cancelling": {"es": "Cancelando la generación… (efectivo en el próximo punto de control)", "de": "Generierung wird abgebrochen… (wirksam am nächsten Kontrollpunkt)", "it": "Annullamento della generazione… (effettivo al prossimo punto di controllo)", "pt": "Cancelando a geração… (efetivo no próximo ponto de verificação)", "ru": "Отмена генерации… (вступит в силу на следующей контрольной точке)", "zh": "正在取消生成…（在下一个检查点生效）", "ja": "生成をキャンセル中…（次のチェックポイントで有効）", "ko": "생성을 취소하는 중… (다음 체크포인트에서 적용)"},
    "generation_cancelled": {"es": "Generación cancelada — el trabajo ya guardado se conserva.", "de": "Generierung abgebrochen — bereits gespeicherte Arbeit bleibt erhalten.", "it": "Generazione annullata — il lavoro già salvato viene conservato.", "pt": "Geração cancelada — o trabalho já salvo é mantido.", "ru": "Генерация отменена — уже сохранённая работа остаётся.", "zh": "生成已取消——已保存的工作会保留。", "ja": "生成をキャンセルしました — すでに保存された作業は保持されます。", "ko": "생성이 취소되었습니다 — 이미 저장된 작업은 유지됩니다."},
    "generation_target": {"es": "¿Qué generar?", "de": "Was generieren?", "it": "Cosa generare?", "pt": "O que gerar?", "ru": "Что генерировать?", "zh": "生成什么？", "ja": "何を生成しますか？", "ko": "무엇을 생성할까요?"},
    "generation_source": {"es": "Fuente de información", "de": "Informationsquelle", "it": "Fonte di informazioni", "pt": "Fonte de informação", "ru": "Источник информации", "zh": "信息来源", "ja": "情報ソース", "ko": "정보 출처"},
    "populate_auto": {"es": "Automático: Deducir de las otras pestañas", "de": "Automatisch: Aus den vorhandenen Reitern ableiten", "it": "Automatico: Deduci dalle altre schede", "pt": "Automático: Inferir das outras abas", "ru": "Автоматически: вывести из существующих вкладок", "zh": "自动：从现有选项卡推断", "ja": "自動：既存のタブから推測", "ko": "자동: 기존 탭에서 추론"},
    "populate_custom": {"es": "Personalizado: Usar un prompt narrativo específico", "de": "Benutzerdefiniert: Einen bestimmten narrativen Prompt verwenden", "it": "Personalizzato: Usa un prompt narrativo specifico", "pt": "Personalizado: Usar um prompt narrativo específico", "ru": "Свой вариант: использовать конкретный нарративный промпт", "zh": "自定义：使用特定的叙事提示", "ja": "カスタム：特定の物語プロンプトを使用", "ko": "사용자 지정: 특정 서사 프롬프트 사용"},
    "populate_warning": {"es": "Nota: La generación guardará primero tus cambios automáticamente.", "de": "Hinweis: Die Generierung speichert zuerst automatisch deine Änderungen.", "it": "Nota: La generazione salverà prima automaticamente le tue modifiche.", "pt": "Nota: A geração salvará primeiro suas alterações automaticamente.", "ru": "Примечание: генерация сначала автоматически сохранит ваши изменения.", "zh": "注意：生成会先自动保存你的更改。", "ja": "注意：生成は先にあなたの変更を自動保存します。", "ko": "참고: 생성은 먼저 변경 사항을 자동으로 저장합니다."},
    "start_generation": {"es": "Iniciar la generación con IA", "de": "KI-Generierung starten", "it": "Avvia la generazione con IA", "pt": "Iniciar a geração com IA", "ru": "Запустить генерацию ИИ", "zh": "开始 AI 生成", "ja": "AI 生成を開始", "ko": "AI 생성 시작"},
    "time_model": {"es": "Modelo de tiempo:", "de": "Zeitmodell:", "it": "Modello temporale:", "pt": "Modelo de tempo:", "ru": "Модель времени:", "zh": "时间模型：", "ja": "時間モデル：", "ko": "시간 모델:"},
    "chronicler_minutes_label": {"es": "Intervalo del Cronista (min en juego):", "de": "Chronist-Intervall (Spielminuten):", "it": "Intervallo del Cronista (min di gioco):", "pt": "Intervalo do Cronista (min no jogo):", "ru": "Интервал Хрониста (игровые мин):", "zh": "编年史官间隔（游戏内分钟）：", "ja": "クロニクラー間隔（ゲーム内分）：", "ko": "기록자 간격 (게임 내 분):"},
    "timekeeper_enabled": {"es": "Relojero IA (tiempo preciso)", "de": "KI-Zeitmesser (präzise Zeit)", "it": "Cronometrista IA (tempo preciso)", "pt": "Relojoeiro IA (tempo preciso)", "ru": "ИИ-хронометрист (точное время)", "zh": "AI 计时员（精确时间）", "ja": "AI 時計係（精密な時間）", "ko": "AI 시간 관리자 (정밀 시간)"},
    "timekeeper_enabled_tooltip": {"es": "Si está activado, una segunda llamada al LLM estima los minutos de juego transcurridos cada turno para un seguimiento preciso del tiempo. Desactívalo para ahorrar una llamada al LLM por turno (el tiempo se estima entonces según el ritmo de la escena).", "de": "Wenn aktiviert, schätzt ein zweiter LLM-Aufruf die pro Zug vergangenen Spielminuten für eine präzise Zeitverfolgung. Deaktiviere es, um einen LLM-Aufruf pro Zug zu sparen (die Zeit wird dann anhand des Szenentempos geschätzt).", "it": "Se attivo, una seconda chiamata all'LLM stima i minuti di gioco trascorsi a ogni turno per un tracciamento preciso del tempo. Disattivalo per risparmiare una chiamata all'LLM per turno (il tempo viene allora stimato dal ritmo della scena).", "pt": "Se ativado, uma segunda chamada ao LLM estima os minutos de jogo decorridos a cada turno para um acompanhamento preciso do tempo. Desative-o para economizar uma chamada ao LLM por turno (o tempo é então estimado pelo ritmo da cena).", "ru": "Если включено, второй вызов LLM оценивает прошедшие игровые минуты каждый ход для точного отслеживания времени. Отключите, чтобы сэкономить один вызов LLM за ход (время тогда оценивается по темпу сцены).", "zh": "启用后，每回合会有第二次 LLM 调用来估算游戏内经过的分钟数，以实现精确的时间跟踪。禁用可每回合节省一次 LLM 调用（届时根据场景节奏估算时间）。", "ja": "有効にすると、毎ターン 2 回目の LLM 呼び出しで経過したゲーム内分数を推定し、正確な時間管理を行います。無効にするとターンごとに LLM 呼び出しを 1 回節約できます（その場合、時間はシーンのペースから推定されます）。", "ko": "활성화하면 매 턴 두 번째 LLM 호출이 경과한 게임 내 분을 추정하여 정밀하게 시간을 추적합니다. 비활성화하면 턴당 LLM 호출 한 번을 절약합니다(이 경우 시간은 장면 속도로 추정됨)."},
    "tab_image": {"es": "Ilustración", "de": "Illustration", "it": "Illustrazione", "pt": "Ilustração", "ru": "Иллюстрация", "zh": "插图", "ja": "イラスト", "ko": "일러스트"},
    "image_enable": {"es": "Activar la generación de imágenes", "de": "Bildgenerierung aktivieren", "it": "Attiva la generazione di immagini", "pt": "Ativar a geração de imagens", "ru": "Включить генерацию изображений", "zh": "启用图像生成", "ja": "画像生成を有効にする", "ko": "이미지 생성 활성화"},
    "image_backend": {"es": "Motor de renderizado:", "de": "Backend:", "it": "Motore di rendering:", "pt": "Motor de renderização:", "ru": "Движок:", "zh": "渲染后端：", "ja": "バックエンド：", "ko": "백엔드:"},
    "image_api_url": {"es": "URL de la API:", "de": "API-URL:", "it": "URL dell'API:", "pt": "URL da API:", "ru": "URL API:", "zh": "API 网址：", "ja": "API の URL：", "ko": "API URL:"},
    "image_width": {"es": "Ancho (píxeles):", "de": "Breite (Pixel):", "it": "Larghezza (pixel):", "pt": "Largura (pixels):", "ru": "Ширина (пиксели):", "zh": "宽度（像素）：", "ja": "幅（ピクセル）：", "ko": "너비(픽셀):"},
    "image_height": {"es": "Alto (píxeles):", "de": "Höhe (Pixel):", "it": "Altezza (pixel):", "pt": "Altura (pixels):", "ru": "Высота (пиксели):", "zh": "高度（像素）：", "ja": "高さ（ピクセル）：", "ko": "높이(픽셀):"},
    "image_steps": {"es": "Pasos de eliminación de ruido:", "de": "Entrauschungsschritte:", "it": "Passi di denoising:", "pt": "Passos de remoção de ruído:", "ru": "Шаги шумоподавления:", "zh": "去噪步数：", "ja": "デノイズのステップ数：", "ko": "디노이즈 단계:"},
    "image_cfg_scale": {"es": "Escala CFG (guiado):", "de": "CFG-Skala (Führung):", "it": "Scala CFG (guida):", "pt": "Escala CFG (orientação):", "ru": "Масштаб CFG (наведение):", "zh": "CFG 比例（引导）：", "ja": "CFG スケール（ガイダンス）：", "ko": "CFG 스케일(가이던스):"},
    "image_workflow": {"es": "Flujo de trabajo de ComfyUI (JSON):", "de": "ComfyUI-Workflow (JSON):", "it": "Workflow ComfyUI (JSON):", "pt": "Fluxo de trabalho ComfyUI (JSON):", "ru": "Рабочий процесс ComfyUI (JSON):", "zh": "ComfyUI 工作流（JSON）：", "ja": "ComfyUI ワークフロー（JSON）：", "ko": "ComfyUI 워크플로 (JSON):"},
    "image_gemini_model": {"es": "Modelo de imagen Gemini:", "de": "Gemini-Bildmodell:", "it": "Modello di immagine Gemini:", "pt": "Modelo de imagem Gemini:", "ru": "Модель изображений Gemini:", "zh": "Gemini 图像模型：", "ja": "Gemini 画像モデル：", "ko": "Gemini 이미지 모델:"},
    "image_timeout": {"es": "Tiempo máx. por imagen (segundos):", "de": "Bild-Zeitlimit (Sekunden):", "it": "Timeout per immagine (secondi):", "pt": "Tempo limite por imagem (segundos):", "ru": "Тайм-аут изображения (секунды):", "zh": "每张图像超时（秒）：", "ja": "画像のタイムアウト（秒）：", "ko": "이미지 제한 시간(초):"},
    "tab_map": {"es": "Mapa", "de": "Karte", "it": "Mappa", "pt": "Mapa", "ru": "Карта", "zh": "地图", "ja": "マップ", "ko": "지도"},
    "hierarchy": {"es": "Jerarquía", "de": "Hierarchie", "it": "Gerarchia", "pt": "Hierarquia", "ru": "Иерархия", "zh": "层级", "ja": "階層", "ko": "계층"},
    "editing_map_of": {"es": "Editando el mapa de", "de": "Karte bearbeiten von", "it": "Modifica della mappa di", "pt": "Editando o mapa de", "ru": "Редактирование карты", "zh": "正在编辑地图：", "ja": "マップを編集中：", "ko": "지도 편집 중:"},
    "add_location": {"es": "Añadir un lugar", "de": "Ort hinzufügen", "it": "Aggiungi un luogo", "pt": "Adicionar um local", "ru": "Добавить место", "zh": "添加地点", "ja": "場所を追加", "ko": "장소 추가"},
    "location_name": {"es": "Nombre del lugar", "de": "Name des Ortes", "it": "Nome del luogo", "pt": "Nome do local", "ru": "Название места", "zh": "地点名称", "ja": "場所の名前", "ko": "장소 이름"},
    "add_connection": {"es": "Añadir una conexión", "de": "Verbindung hinzufügen", "it": "Aggiungi una connessione", "pt": "Adicionar uma conexão", "ru": "Добавить связь", "zh": "添加连接", "ja": "接続を追加", "ko": "연결 추가"},
    "edit_description": {"es": "Modificar la descripción", "de": "Beschreibung bearbeiten", "it": "Modifica la descrizione", "pt": "Editar a descrição", "ru": "Изменить описание", "zh": "编辑描述", "ja": "説明を編集", "ko": "설명 편집"},
    "scale_universe": {"es": "Universo", "de": "Universum", "it": "Universo", "pt": "Universo", "ru": "Вселенная", "zh": "宇宙", "ja": "ユニバース", "ko": "유니버스"},
    "scale_galaxy": {"es": "Galaxia", "de": "Galaxie", "it": "Galassia", "pt": "Galáxia", "ru": "Галактика", "zh": "星系", "ja": "銀河", "ko": "은하"},
    "scale_world": {"es": "Mundo", "de": "Welt", "it": "Mondo", "pt": "Mundo", "ru": "Мир", "zh": "世界", "ja": "世界", "ko": "세계"},
    "scale_country": {"es": "País", "de": "Land", "it": "Paese", "pt": "País", "ru": "Страна", "zh": "国家", "ja": "国", "ko": "국가"},
    "scale_zone": {"es": "Zona", "de": "Zone", "it": "Zona", "pt": "Zona", "ru": "Зона", "zh": "区域", "ja": "ゾーン", "ko": "구역"},
    "scale_city": {"es": "Ciudad", "de": "Stadt", "it": "Città", "pt": "Cidade", "ru": "Город", "zh": "城市", "ja": "都市", "ko": "도시"},
    "scale_district": {"es": "Distrito", "de": "Bezirk", "it": "Distretto", "pt": "Distrito", "ru": "Район", "zh": "区", "ja": "地区", "ko": "지구"},
    "scale_building": {"es": "Edificio", "de": "Gebäude", "it": "Edificio", "pt": "Edifício", "ru": "Здание", "zh": "建筑", "ja": "建物", "ko": "건물"},
    "scale_room": {"es": "Habitación", "de": "Raum", "it": "Stanza", "pt": "Sala", "ru": "Комната", "zh": "房间", "ja": "部屋", "ko": "방"},
    "scale_poi": {"es": "Punto de interés", "de": "Sehenswürdigkeit", "it": "Punto di interesse", "pt": "Ponto de interesse", "ru": "Точка интереса", "zh": "兴趣点", "ja": "注目地点", "ko": "관심 지점"},
}

LANGS = ["es", "de", "it", "pt", "ru", "zh", "ja", "ko"]


def main() -> int:
    en = tomllib.loads((LOCALES / "en.toml").read_text(encoding="utf-8"))
    # Sanity : toute clé EN absente d'au moins une langue doit être couverte par T.
    total_added = 0
    for lang in LANGS:
        path = LOCALES / f"{lang}.toml"
        doc = tomlkit.parse(path.read_text(encoding="utf-8"))
        existing = set(tomllib.loads(path.read_text(encoding="utf-8")))
        added = 0
        for key in en:  # ordre EN = ordre de référence
            if key in existing:
                continue
            if key not in T or lang not in T[key]:
                raise SystemExit(f"Traduction manquante dans le script : {key} / {lang}")
            doc[key] = T[key][lang]
            added += 1
        path.write_text(tomlkit.dumps(doc), encoding="utf-8")
        print(f"{lang}: +{added} clés")
        total_added += added
    print(f"Total ajouté : {total_added}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
