"""axiom/storage_registry.py

Central persistence registry and storage policies for universe definitions and
save states in Axiom AI.

Replaces hardcoded table lists across checkpoint rewind, save forking,
packaging, and savestore copies with unified declarative policies (Phase 0c).

Policies:

- ``EVENTS`` / ``STEP_KEYED``: rows carry a step column. Rewind deletes the rows
  ``> N``; fork copies the rows ``<= N`` **generically** from the declared
  ``columns`` (``id_column`` regenerated: new AUTOINCREMENT value or new uuid).
  A new step-keyed table only needs to be declared, not coded.
- ``VERSIONED_KV``: definition tables and per-save rows that rewind/fork leave alone.
- ``DERIVED``: caches rebuilt from the journal (``State_Cache``): never copied or
  rewound by the registry; ``CheckpointManager.rewind`` / ``fork_save`` rebuild them.
- ``CUSTOM``: a handler is unavoidable. Each core handler says why (ids stored
  inside JSON payloads that must be remapped with ONE mapping, or snapshot-based
  state that cannot be filtered by a step column).

Stores outside the save database (vector memory, illustration files) are
registered by mods as *external* storages: they are rewound **after** the SQL
rewind is committed, never inside the transaction.
"""

from __future__ import annotations

import json
import sqlite3
import threading
import uuid
from dataclasses import dataclass
from enum import Enum
from typing import Any, Callable

from axiom.logger import logger


class StoragePolicy(Enum):
    EVENTS = "events"                     # Journal append-only réductible (Event_Log)
    STEP_KEYED = "step_keyed_table"       # Table SQL avec colonne step/turn explicite
    VERSIONED_KV = "versioned_kv"         # Clé-valeur avec borne de validité temporelle
    DERIVED = "derived"                   # Cache reconstruit depuis le journal (State_Cache)
    CUSTOM = "custom"                     # Gestionnaire externe (Vector DB, snapshots, etc.)


@dataclass(frozen=True)
class TableStorageSpec:
    table_name: str
    policy: StoragePolicy
    step_column: str | None = "turn_id"   # Colonne horodatée pour STEP_KEYED
    is_runtime: bool = True               # True = runtime/save, False = définition d'univers
    columns: tuple[str, ...] | None = None
    custom_rewind: Callable[..., Any] | None = None
    custom_fork: Callable[..., Any] | None = None
    # Identifier column regenerated by the generic fork (None = natural key kept).
    id_column: str | None = None
    id_autoincrement: bool = False        # True: INTEGER AUTOINCREMENT; False: new uuid4 text
    # The table carries a save_id column (per-save rows). False for per-database
    # tables (Mod_Schema_Versions) and for external stores.
    save_scoped: bool = True
    # Copied by the fork handler of another table (ids inside JSON payloads that
    # must share that handler's id mapping). The generic fork skips it.
    fork_with: str | None = None
    # Non-SQL store (vector DB, files): rewound/forked after the SQL commit; conn is None.
    external: bool = False
    owner: str | None = None              # Mod id that registered the spec (None = core)


# ---------------------------------------------------------------------------
# Custom Rollback & Fork Callbacks (core)
# ---------------------------------------------------------------------------
# Core fork handlers receive ``id_maps``: {table_name: {old_id: new_id}} filled
# by the tables forked before them (registry order), so ids that are stored in
# JSON (`sources`) can be rewritten.

def _remap_fact_sources(raw: Any, fact_map: dict[Any, Any]) -> str:
    """Rewrite an Observations ``sources`` list ([{fact_id, turn_id}]) with the forked fact ids."""
    try:
        sources = json.loads(raw) if isinstance(raw, str) else (raw or [])
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Invalid Observations.sources JSON: {raw!r}") from exc
    out = []
    for src in sources if isinstance(sources, list) else []:
        if not isinstance(src, dict):
            continue
        new = dict(src)
        fid = src.get("fact_id")
        try:
            fid = int(fid) if fid is not None else None
        except (TypeError, ValueError):
            fid = None
        # A fact at a turn after the fork point was not copied: the rollback below
        # drops that source anyway (its turn_id > N). Never keep a source id.
        new["fact_id"] = fact_map.get(fid) if fid is not None else None
        out.append(new)
    return json.dumps(out, ensure_ascii=False)


def _rewind_observations(conn: sqlite3.Connection, save_id: str, target_turn: int) -> None:
    from axiom.observations import rollback_observations
    rollback_observations(conn, save_id, target_turn)


def _fork_observations(
    conn: sqlite3.Connection, src_save_id: str, dst_save_id: str, target_turn: int,
    *, id_maps: dict[str, dict[Any, Any]],
) -> None:
    """Beliefs at the fork point = copy of the beliefs born <= N, then the same
    rollback as a rewind to N (sources > N dropped, proof_count recomputed,
    updated_turn_id clamped, stale flagged). Custom because ``sources`` holds
    fact ids (JSON) that must follow the forked Facts ids.
    """
    from axiom.observations import rollback_observations
    from axiom.schema import ensure_observations_table

    ensure_observations_table(conn)
    fact_map = id_maps.get("Facts", {})
    obs_map: dict[Any, Any] = {}
    rows = conn.execute(
        "SELECT observation_id, subject, statement, proof_count, sources, history, "
        "created_turn_id, updated_turn_id, stale "
        "FROM Observations WHERE save_id = ? AND created_turn_id <= ? ORDER BY observation_id;",
        (src_save_id, target_turn),
    ).fetchall()
    for r in rows:
        cur = conn.execute(
            "INSERT INTO Observations (save_id, subject, statement, proof_count, sources, "
            "history, created_turn_id, updated_turn_id, stale) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);",
            (dst_save_id, r[1], r[2], r[3], _remap_fact_sources(r[4], fact_map), r[5], r[6], r[7], r[8]),
        )
        obs_map[int(r[0])] = cur.lastrowid
    id_maps["Observations"] = obs_map
    rollback_observations(conn, dst_save_id, target_turn)


def _rewind_mental_models(conn: sqlite3.Connection, save_id: str, target_turn: int) -> None:
    from axiom.mental_models import rollback_mental_models
    rollback_mental_models(conn, save_id, target_turn)


def _fork_mental_models(
    conn: sqlite3.Connection, src_save_id: str, dst_save_id: str, target_turn: int,
    *, id_maps: dict[str, dict[Any, Any]],
) -> None:
    """Same rule as the beliefs: copy the models born <= N, then rewind them to N.
    Custom because ``sources`` holds observation ids (JSON)."""
    from axiom.mental_models import rollback_mental_models
    from axiom.schema import ensure_mental_models_table

    ensure_mental_models_table(conn)
    obs_map = id_maps.get("Observations", {})
    rows = conn.execute(
        "SELECT model_id, subject, summary, sources, created_turn_id, updated_turn_id, stale "
        "FROM Mental_Models WHERE save_id = ? AND created_turn_id <= ? ORDER BY model_id;",
        (src_save_id, target_turn),
    ).fetchall()
    model_map: dict[Any, Any] = {}
    for r in rows:
        try:
            sources = json.loads(r[3]) if r[3] else []
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Invalid Mental_Models.sources JSON: {r[3]!r}") from exc
        remapped = []
        for s in sources if isinstance(sources, list) else []:
            try:
                old = int(s)
            except (TypeError, ValueError):
                continue
            if old in obs_map:
                remapped.append(obs_map[old])
        cur = conn.execute(
            "INSERT INTO Mental_Models (save_id, subject, summary, sources, created_turn_id, "
            "updated_turn_id, stale) VALUES (?, ?, ?, ?, ?, ?, ?);",
            (dst_save_id, r[1], r[2], json.dumps(remapped), r[4], r[5], r[6]),
        )
        model_map[int(r[0])] = cur.lastrowid
    id_maps["Mental_Models"] = model_map
    rollback_mental_models(conn, dst_save_id, target_turn)


def _rewind_modifiers(conn: sqlite3.Connection, save_id: str, target_turn: int) -> None:
    from axiom.modifiers import rollback_modifiers
    rollback_modifiers(conn, save_id, target_turn)


def _fork_modifiers(
    conn: sqlite3.Connection, src_save_id: str, dst_save_id: str, target_turn: int,
    *, id_maps: dict[str, dict[Any, Any]],
) -> None:
    """Active_Modifiers at the fork point + the Modifier_Snapshots <= N.

    Custom because modifiers decay in minutes (not event-sourced): the state at N
    only exists in the snapshot of turn N, and the snapshots store modifier ids
    (JSON) that must follow the regenerated ids (one mapping for both).
    """
    from axiom.saves import _max_turn
    from axiom.schema import ensure_modifier_snapshots_table

    ensure_modifier_snapshots_table(conn)
    id_map: dict[str, str] = {}

    def _new(old: Any) -> str:
        key = str(old)
        if key not in id_map:
            id_map[key] = str(uuid.uuid4())
        return id_map[key]

    if target_turn < _max_turn(conn, src_save_id):
        # Same lookup as modifiers_at / rollback_modifiers. No snapshot row for
        # turn N means "no modifiers then": never fall back on the present
        # modifiers (they belong to later turns).
        row = conn.execute(
            "SELECT state_json FROM Modifier_Snapshots WHERE save_id = ? AND turn_id = ?;",
            (src_save_id, target_turn),
        ).fetchone()
        mod_rows = json.loads(row[0]) if row and row[0] else []
    else:
        mod_rows = [
            dict(r) for r in conn.execute(
                "SELECT modifier_id, entity_id, stat_key, delta, minutes_remaining "
                "FROM Active_Modifiers WHERE save_id = ?;",
                (src_save_id,),
            ).fetchall()
        ]

    conn.executemany(
        "INSERT INTO Active_Modifiers (modifier_id, save_id, entity_id, stat_key, delta, minutes_remaining) "
        "VALUES (?, ?, ?, ?, ?, ?);",
        [(_new(r["modifier_id"]), dst_save_id, r["entity_id"], r["stat_key"], r["delta"],
          r["minutes_remaining"]) for r in mod_rows],
    )
    for snap in conn.execute(
        "SELECT turn_id, state_json FROM Modifier_Snapshots WHERE save_id = ? AND turn_id <= ?;",
        (src_save_id, target_turn),
    ).fetchall():
        state = [{**m, "modifier_id": _new(m["modifier_id"])} for m in json.loads(snap[1] or "[]")]
        conn.execute(
            "INSERT OR REPLACE INTO Modifier_Snapshots (save_id, turn_id, state_json) VALUES (?, ?, ?);",
            (dst_save_id, snap[0], json.dumps(state)),
        )
    id_maps["Active_Modifiers"] = id_map


def _rewind_inventory(conn: sqlite3.Connection, save_id: str, target_turn: int) -> None:
    from axiom.inventory import rollback_inventory
    rollback_inventory(conn, save_id, target_turn)


def _fork_item_instances(
    conn: sqlite3.Connection, src_save_id: str, dst_save_id: str, target_turn: int,
    *, id_maps: dict[str, dict[Any, Any]],
) -> None:
    """Nested inventory at the fork point + Inventory_Snapshots <= N.

    Custom because instance ids are referenced by other instances (containers)
    and inside the snapshots' JSON: one mapping shared by rows and snapshots.
    """
    from axiom.saves import _fork_item_instances as _fork
    _fork(conn, src_save_id, dst_save_id, target_turn)


def _fork_legacy_inventory(
    conn: sqlite3.Connection, src_save_id: str, dst_save_id: str, target_turn: int,
    *, id_maps: dict[str, dict[Any, Any]],
) -> None:
    """Legacy flat bag (kept for old saves; not turn-keyed, so copied as is)."""
    inv_rows = conn.execute(
        "SELECT entity_id, item_id, quantity FROM Items_Inventory WHERE save_id = ?;",
        (src_save_id,),
    ).fetchall()
    conn.executemany(
        "INSERT INTO Items_Inventory (save_id, entity_id, item_id, quantity) VALUES (?, ?, ?, ?);",
        [(dst_save_id, r[0], r[1], r[2]) for r in inv_rows],
    )


# ---------------------------------------------------------------------------
# Canonical Core Storage Registry
# ---------------------------------------------------------------------------
# Registry order matters for the fork: a table whose ids are referenced by a
# later one comes first (Facts -> Observations -> Mental_Models).

CORE_STORAGE_REGISTRY: list[TableStorageSpec] = [
    # Définition pure (non affectée par le rewind, copiée au fork)
    TableStorageSpec("Universe_Meta", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("key", "value")),
    TableStorageSpec("Entity_Types", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("type_id", "name", "role", "description", "is_builtin")),
    TableStorageSpec("Stat_Definitions", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("stat_id", "name", "description", "value_type", "parameters")),
    TableStorageSpec("Stat_Type_Links", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("stat_id", "type_id")),
    TableStorageSpec("Entities", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("entity_id", "entity_type", "entity_role", "name", "description", "is_active", "origin")),
    TableStorageSpec("Entity_Stats", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("entity_id", "stat_key", "stat_value")),
    TableStorageSpec("Rules", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("rule_id", "priority", "conditions", "actions", "target_entity")),
    TableStorageSpec("Lore_Book", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("entry_id", "category", "name", "keywords", "content")),
    TableStorageSpec("Locations", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("location_id", "name", "scale", "parent_id", "description", "x", "y")),
    TableStorageSpec("Location_Connections", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("source_id", "target_id", "distance_km")),
    TableStorageSpec("Scheduled_Events", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("event_id", "trigger_minute", "title", "description")),
    TableStorageSpec("Item_Definitions", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("item_id", "name", "description", "category", "weight", "rarity", "is_container", "capacity")),
    TableStorageSpec("Story_Setup", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("setup_id", "question", "type", "options", "max_selections", "priority")),

    # Runtime / Sauvegarde (affecté par le rewind et le fork)
    # Schema versions of the mods' tables in THIS database: owned by the save db
    # (never copied from the universe, which may not have the mods' tables), not
    # per save_id, so neither forked, rewound nor purged.
    TableStorageSpec("Mod_Schema_Versions", StoragePolicy.VERSIONED_KV, is_runtime=True,
                     columns=("mod_id", "schema_version", "installed_at"), save_scoped=False),
    TableStorageSpec("Saves", StoragePolicy.VERSIONED_KV, is_runtime=True,
                     columns=("save_id", "player_name", "difficulty", "last_updated", "player_persona", "created_at")),
    TableStorageSpec("Event_Log", StoragePolicy.EVENTS, step_column="turn_id", is_runtime=True,
                     columns=("event_id", "save_id", "turn_id", "event_type", "target_entity", "payload"),
                     id_column="event_id", id_autoincrement=True),
    TableStorageSpec("Timeline", StoragePolicy.STEP_KEYED, step_column="turn_id", is_runtime=True,
                     columns=("event_id", "save_id", "turn_id", "in_game_time", "description"),
                     id_column="event_id", id_autoincrement=True),
    TableStorageSpec("State_Cache", StoragePolicy.DERIVED, step_column=None, is_runtime=True,
                     columns=("save_id", "entity_id", "stat_key", "stat_value")),
    TableStorageSpec("Snapshots", StoragePolicy.STEP_KEYED, step_column="turn_id", is_runtime=True,
                     columns=("save_id", "turn_id", "state_json")),
    TableStorageSpec("Fired_Scheduled_Events", StoragePolicy.STEP_KEYED, step_column="fired_turn_id", is_runtime=True,
                     columns=("save_id", "event_id", "fired_turn_id")),
    TableStorageSpec("Session_Lore", StoragePolicy.STEP_KEYED, step_column="origin_turn", is_runtime=True,
                     columns=("entry_id", "save_id", "category", "name", "keywords", "content", "origin_turn"),
                     id_column="entry_id"),
    TableStorageSpec("Facts", StoragePolicy.STEP_KEYED, step_column="turn_id", is_runtime=True,
                     columns=("fact_id", "save_id", "turn_id", "fact_type", "who", "what",
                              "fact_when", "fact_where", "why", "entities", "statement"),
                     id_column="fact_id", id_autoincrement=True),
    TableStorageSpec("Observations", StoragePolicy.CUSTOM, is_runtime=True,
                     columns=("observation_id", "save_id", "subject", "statement",
                              "proof_count", "sources", "history", "created_turn_id",
                              "updated_turn_id", "stale"),
                     custom_rewind=_rewind_observations, custom_fork=_fork_observations),
    TableStorageSpec("Mental_Models", StoragePolicy.CUSTOM, is_runtime=True,
                     columns=("model_id", "save_id", "subject", "summary", "sources",
                              "created_turn_id", "updated_turn_id", "stale"),
                     custom_rewind=_rewind_mental_models, custom_fork=_fork_mental_models),
    TableStorageSpec("Active_Modifiers", StoragePolicy.CUSTOM, is_runtime=True,
                     columns=("modifier_id", "save_id", "entity_id", "stat_key", "delta", "minutes_remaining"),
                     custom_rewind=_rewind_modifiers, custom_fork=_fork_modifiers),
    TableStorageSpec("Modifier_Snapshots", StoragePolicy.STEP_KEYED, step_column="turn_id", is_runtime=True,
                     columns=("save_id", "turn_id", "state_json"), fork_with="Active_Modifiers"),
    TableStorageSpec("Items_Inventory", StoragePolicy.CUSTOM, is_runtime=True,
                     columns=("save_id", "entity_id", "item_id", "quantity"),
                     custom_fork=_fork_legacy_inventory),
    TableStorageSpec("Item_Instances", StoragePolicy.CUSTOM, is_runtime=True,
                     columns=("instance_id", "save_id", "item_id", "quantity", "holder_kind", "holder_id"),
                     custom_rewind=_rewind_inventory, custom_fork=_fork_item_instances),
    TableStorageSpec("Inventory_Snapshots", StoragePolicy.STEP_KEYED, step_column="turn_id", is_runtime=True,
                     columns=("save_id", "turn_id", "state_json"), fork_with="Item_Instances"),
]

_REGISTRY_LOCK = threading.RLock()


# ---------------------------------------------------------------------------
# Public Helper Functions
# ---------------------------------------------------------------------------

def _specs() -> list[TableStorageSpec]:
    with _REGISTRY_LOCK:
        return list(CORE_STORAGE_REGISTRY)


def get_definition_tables() -> list[str]:
    """Return all universe definition table names."""
    return [spec.table_name for spec in _specs() if not spec.is_runtime]


def get_runtime_tables() -> list[str]:
    """Return the per-save SQL tables, ``Saves`` last (purge order: children first).

    External stores (vector memory, files) and per-database tables
    (``Mod_Schema_Versions``) are not save rows and are not listed.
    """
    tables = [
        spec.table_name for spec in _specs()
        if spec.is_runtime and spec.save_scoped and not spec.external
    ]
    ordered = [t for t in reversed(tables) if t != "Saves"]
    if "Saves" in tables:
        ordered.append("Saves")
    return ordered


def get_definition_copy_specs() -> list[tuple[str, tuple[str, ...]]]:
    """Return (table_name, columns) pairs for copying universe definitions into a save db."""
    return [
        (spec.table_name, spec.columns)
        for spec in _specs()
        if not spec.is_runtime and spec.columns is not None
    ]


def get_runtime_copy_specs() -> list[tuple[str, tuple[str, ...]]]:
    """Return (table_name, columns) pairs for copying the per-save runtime rows."""
    return [
        (spec.table_name, spec.columns)
        for spec in _specs()
        if spec.is_runtime and spec.save_scoped and not spec.external and spec.columns is not None
    ]


def _table_exists(conn: sqlite3.Connection, table: str) -> bool:
    return conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?;", (table,)
    ).fetchone() is not None


def execute_rewind(
    conn: sqlite3.Connection,
    save_id: str,
    target_turn_id: int,
    *,
    external: bool = True,
) -> dict[str, int]:
    """Execute unified rewind on all registered SQL tables, on the caller's transaction.

    ``external=False`` leaves the non-SQL stores alone: the engine path
    (:meth:`axiom.checkpoint.CheckpointManager.rewind`) commits the SQL first,
    then calls :func:`execute_external_rewind`. ``external=True`` (default, kept
    for direct callers) runs them at the end of this call.
    """
    from axiom.schema import (
        ensure_facts_table,
        ensure_fired_event_turn_column,
        ensure_inventory_snapshots_table,
        ensure_modifier_snapshots_table,
    )

    ensure_fired_event_turn_column(conn)
    ensure_facts_table(conn)
    ensure_modifier_snapshots_table(conn)
    ensure_inventory_snapshots_table(conn)

    deleted_count = 0
    specs = [s for s in _specs() if not s.external]

    # 1. EVENTS (Event_Log)
    for spec in specs:
        if spec.policy == StoragePolicy.EVENTS:
            cur = conn.execute(
                f"DELETE FROM {spec.table_name} WHERE save_id = ? AND {spec.step_column} > ?;",
                (save_id, target_turn_id),
            )
            deleted_count += cur.rowcount or 0

    # 2. STEP_KEYED tables (a table not created yet in an old db has nothing to rewind)
    for spec in specs:
        if spec.policy == StoragePolicy.STEP_KEYED and _table_exists(conn, spec.table_name):
            conn.execute(
                f"DELETE FROM {spec.table_name} WHERE save_id = ? AND {spec.step_column} > ?;",
                (save_id, target_turn_id),
            )

    # 3. CUSTOM handlers
    for spec in specs:
        if spec.policy == StoragePolicy.CUSTOM and spec.custom_rewind is not None:
            spec.custom_rewind(conn, save_id, target_turn_id)

    if external:
        execute_external_rewind(save_id, target_turn_id)

    return {"deleted_events": deleted_count, "rebuilt_to_turn": target_turn_id}


def execute_external_rewind(save_id: str, target_turn_id: int) -> list[str]:
    """Rewind the external (non-SQL) stores. Call it AFTER the SQL rewind is committed.

    A failing store does not stop the others; it is logged and its name returned
    (the SQL state is already committed and stays the source of truth).
    """
    failed: list[str] = []
    for spec in _specs():
        if spec.external and spec.custom_rewind is not None:
            try:
                spec.custom_rewind(None, save_id, target_turn_id)
            except Exception:
                logger.exception(
                    "External storage '%s' (mod %s) failed to rewind save %s to turn %d",
                    spec.table_name, spec.owner, save_id, target_turn_id,
                )
                failed.append(spec.table_name)
    return failed


def _fork_generic(
    conn: sqlite3.Connection,
    spec: TableStorageSpec,
    src_save_id: str,
    dst_save_id: str,
    at_turn: int,
) -> dict[Any, Any]:
    """Copy the rows ``step_column <= at_turn`` of a step-keyed table from its
    declared columns. Returns the {old_id: new_id} mapping (empty without id_column)."""
    if spec.columns is None or spec.step_column is None:
        raise ValueError(f"Step-keyed table '{spec.table_name}' needs columns and a step_column.")
    data_cols = [c for c in spec.columns if c not in ("save_id", spec.id_column)]
    select_cols = ([spec.id_column] if spec.id_column else []) + data_cols
    order = f" ORDER BY {spec.id_column}" if spec.id_autoincrement else ""
    rows = conn.execute(
        f"SELECT {', '.join(select_cols)} FROM {spec.table_name} "
        f"WHERE save_id = ? AND {spec.step_column} <= ?{order};",
        (src_save_id, at_turn),
    ).fetchall()

    id_map: dict[Any, Any] = {}
    insert_cols = ["save_id"] + data_cols
    if spec.id_column and not spec.id_autoincrement:
        insert_cols = [spec.id_column] + insert_cols
    sql = (
        f"INSERT INTO {spec.table_name} ({', '.join(insert_cols)}) "
        f"VALUES ({', '.join('?' * len(insert_cols))});"
    )
    for row in rows:
        values = list(row)
        old_id = values.pop(0) if spec.id_column else None
        params = [dst_save_id] + values
        if spec.id_column and not spec.id_autoincrement:
            new_id: Any = str(uuid.uuid4())
            params = [new_id] + params
            conn.execute(sql, params)
        else:
            new_id = conn.execute(sql, params).lastrowid
        if spec.id_column:
            id_map[old_id] = new_id
    return id_map


def execute_fork(
    conn: sqlite3.Connection,
    src_save_id: str,
    dst_save_id: str,
    at_turn: int,
    *,
    external: bool = True,
) -> dict[str, dict[Any, Any]]:
    """Copy all registered runtime tables from src_save_id up to at_turn into dst_save_id.

    Generic for EVENTS / STEP_KEYED tables (declared columns, ids regenerated);
    CUSTOM tables use their handler. Errors propagate: a fork never silently
    drops data. Returns the id mappings {table: {old_id: new_id}}.
    ``external=False``: the caller runs :func:`execute_external_fork` after its commit.
    """
    from axiom.schema import (
        ensure_facts_table,
        ensure_fired_event_turn_column,
        ensure_inventory_snapshots_table,
        ensure_modifier_snapshots_table,
    )
    ensure_fired_event_turn_column(conn)
    ensure_facts_table(conn)
    ensure_modifier_snapshots_table(conn)
    ensure_inventory_snapshots_table(conn)

    id_maps: dict[str, dict[Any, Any]] = {}
    for spec in _specs():
        if not spec.is_runtime or not spec.save_scoped or spec.external or spec.fork_with:
            continue
        if spec.custom_fork is not None:
            if spec.owner is None:
                spec.custom_fork(conn, src_save_id, dst_save_id, at_turn, id_maps=id_maps)
            else:
                spec.custom_fork(conn, src_save_id, dst_save_id, at_turn)
        elif spec.policy in (StoragePolicy.EVENTS, StoragePolicy.STEP_KEYED):
            if _table_exists(conn, spec.table_name):
                id_maps[spec.table_name] = _fork_generic(conn, spec, src_save_id, dst_save_id, at_turn)

    if external:
        execute_external_fork(src_save_id, dst_save_id, at_turn)
    return id_maps


def execute_external_fork(src_save_id: str, dst_save_id: str, at_turn: int) -> list[str]:
    """Fork the external (non-SQL) stores. Call it AFTER the SQL fork is committed."""
    failed: list[str] = []
    for spec in _specs():
        if spec.external and spec.custom_fork is not None:
            try:
                spec.custom_fork(None, src_save_id, dst_save_id, at_turn)
            except Exception:
                logger.exception(
                    "External storage '%s' (mod %s) failed to fork save %s at turn %d",
                    spec.table_name, spec.owner, src_save_id, at_turn,
                )
                failed.append(spec.table_name)
    return failed


def register_table_storage(spec: TableStorageSpec) -> TableStorageSpec | None:
    """Register or replace a table storage specification. Returns the replaced spec."""
    with _REGISTRY_LOCK:
        for i, s in enumerate(CORE_STORAGE_REGISTRY):
            if s.table_name == spec.table_name:
                CORE_STORAGE_REGISTRY[i] = spec
                return s
        CORE_STORAGE_REGISTRY.append(spec)
        return None


def register_custom_storage(
    table_name: str,
    rewind_callback: Callable[[sqlite3.Connection | None, str, int], None] | None = None,
    fork_callback: Callable[[sqlite3.Connection | None, str, str, int], None] | None = None,
    *,
    owner: str | None = None,
) -> TableStorageSpec:
    """Register an external (non-SQL) store: vector DB, generated files...

    Its callbacks run after the SQL rewind/fork is committed and receive
    ``conn=None``. Mods should go through ``ModContext.register_storage`` so the
    registration is removed when the mod is disabled (D11).
    """
    spec = TableStorageSpec(
        table_name=table_name,
        policy=StoragePolicy.CUSTOM,
        step_column=None,
        is_runtime=True,
        custom_rewind=rewind_callback,
        custom_fork=fork_callback,
        save_scoped=False,
        external=True,
        owner=owner,
    )
    register_table_storage(spec)
    return spec


def unregister_storage(spec: TableStorageSpec) -> bool:
    """Remove exactly this registration (a newer one with the same name is kept)."""
    with _REGISTRY_LOCK:
        for i, s in enumerate(CORE_STORAGE_REGISTRY):
            if s is spec:
                del CORE_STORAGE_REGISTRY[i]
                return True
    return False


# ---------------------------------------------------------------------------
# Mod schema migrations (per save database)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ModMigrations:
    mod_id: str
    target_version: int
    migrations: dict[int, Callable[[sqlite3.Connection], None]]


_MOD_MIGRATIONS: dict[str, ModMigrations] = {}


def register_mod_migrations(
    mod_id: str,
    target_version: int,
    migrations: dict[int, Callable[[sqlite3.Connection], None]],
) -> ModMigrations:
    """Declare a mod's table migrations (version N -> N+1 callables).

    They are applied to every save database the engine opens or creates
    (:func:`apply_registered_mod_migrations`), tracked in ``Mod_Schema_Versions``.
    """
    entry = ModMigrations(mod_id, int(target_version), dict(migrations))
    with _REGISTRY_LOCK:
        _MOD_MIGRATIONS[mod_id] = entry
    return entry


def unregister_mod_migrations(entry: ModMigrations) -> None:
    with _REGISTRY_LOCK:
        if _MOD_MIGRATIONS.get(entry.mod_id) is entry:
            del _MOD_MIGRATIONS[entry.mod_id]


def get_registered_mod_migrations() -> list[ModMigrations]:
    with _REGISTRY_LOCK:
        return list(_MOD_MIGRATIONS.values())


def apply_registered_mod_migrations(db_path: str) -> list[str]:
    """Bring the mods' tables of ``db_path`` to their declared versions.

    A failing migration raises (its own transaction is rolled back): the save
    must not be played with a half-migrated mod schema. Returns the mod ids processed.
    """
    from axiom.schema import apply_mod_migrations

    done: list[str] = []
    for entry in get_registered_mod_migrations():
        apply_mod_migrations(str(db_path), entry.mod_id, entry.target_version, entry.migrations)
        done.append(entry.mod_id)
    return done
