"""axiom/storage_registry.py

Central persistence registry and storage policies for universe definitions and
save states in Axiom AI.

Replaces hardcoded table lists across checkpoint rewind, save forking,
packaging, and savestore copies with unified declarative policies (Phase 0c).

Policies:

- ``EVENTS`` / ``STEP_KEYED``: rows carry a step column. Rewind deletes the rows
  ``> N``; fork copies the rows ``<= N`` **generically** from the declared
  ``columns`` (``id_column`` regenerated: new AUTOINCREMENT value or new uuid).
  A new step-keyed table only needs to be declared, not coded.
- ``VERSIONED_KV``: definition tables and per-save rows that rewind/fork leave alone.
- ``DERIVED``: caches rebuilt from the journal (``State_Cache``): never copied or
  rewound by the registry; ``CheckpointManager.rewind`` / ``fork_save`` rebuild them.
- ``CUSTOM``: a handler is unavoidable. Each core handler says why (ids stored
  inside JSON payloads that must be remapped with ONE mapping, or snapshot-based
  state that cannot be filtered by a step column).

Stores outside the save database (vector memory, illustration files) are
registered by mods as *external* storages: they are rewound **after** the SQL
rewind is committed, never inside the transaction.
"""

from __future__ import annotations

import json
import sqlite3
import threading
import uuid
from dataclasses import dataclass
from enum import Enum
from typing import Any, Callable

from axiom.logger import logger


class StoragePolicy(Enum):
    EVENTS = "events"                     # Journal append-only réductible (Event_Log)
    STEP_KEYED = "step_keyed_table"       # Table SQL avec colonne step/turn explicite
    VERSIONED_KV = "versioned_kv"         # Clé-valeur avec borne de validité temporelle
    DERIVED = "derived"                   # Cache reconstruit depuis le journal (State_Cache)
    CUSTOM = "custom"                     # Gestionnaire externe (Vector DB, snapshots, etc.)


@dataclass(frozen=True)
class TableStorageSpec:
    table_name: str
    policy: StoragePolicy
    step_column: str | None = "turn_id"   # Colonne horodatée pour STEP_KEYED
    is_runtime: bool = True               # True = runtime/save, False = définition d'univers
    columns: tuple[str, ...] | None = None
    custom_rewind: Callable[..., Any] | None = None
    custom_fork: Callable[..., Any] | None = None
    # End-of-turn capture (conn, save_id, turn_id), run in the turn's transaction for
    # every registered storage — including those of disabled mods (their data stays
    # consistent with rewinds, owner decision 2026-10-03).
    custom_snapshot: Callable[..., Any] | None = None
    # Save-editor section of a mod's data (see axiom.kernel.manifest): name and
    # handlers state(conn, save_id, turn_id, present) -> (rows, historical),
    # load(conn, save_id, rows, turn_id, replace), diff(before, after) -> rows.
    section: str | None = None
    custom_state: Callable[..., Any] | None = None
    custom_load: Callable[..., Any] | None = None
    custom_diff: Callable[..., Any] | None = None
    # Identifier column regenerated by the generic fork (None = natural key kept).
    id_column: str | None = None
    id_autoincrement: bool = False        # True: INTEGER AUTOINCREMENT; False: new uuid4 text
    # The table carries a save_id column (per-save rows). False for per-database
    # tables (Mod_Schema_Versions) and for external stores.
    save_scoped: bool = True
    # Copied by the fork handler of another table (ids inside JSON payloads that
    # must share that handler's id mapping). The generic fork skips it.
    fork_with: str | None = None
    # Non-SQL store (vector DB, files): rewound/forked after the SQL commit; conn is None.
    external: bool = False
    owner: str | None = None              # Mod id that registered the spec (None = core)


# ---------------------------------------------------------------------------
# Custom Rollback & Fork Callbacks (core)
# ---------------------------------------------------------------------------
# Core fork handlers receive ``id_maps``: {table_name: {old_id: new_id}} filled
# by the tables forked before them (registry order), so ids that are stored in
# JSON (`sources`) can be rewritten.







def _rewind_mod_kv(conn: sqlite3.Connection, save_id: str, target_turn: int) -> None:
    from axiom.schema import ensure_mod_kv_table
    ensure_mod_kv_table(conn)
    conn.execute(
        "DELETE FROM Mod_KV WHERE save_id = ? AND from_step > ?;",
        (save_id, target_turn),
    )
    conn.execute(
        "UPDATE Mod_KV SET to_step = NULL WHERE save_id = ? AND to_step > ?;",
        (save_id, target_turn),
    )


def _fork_mod_kv(
    conn: sqlite3.Connection, src_save_id: str, dst_save_id: str, target_turn: int,
    **kwargs: Any,
) -> None:
    from axiom.schema import ensure_mod_kv_table
    ensure_mod_kv_table(conn)
    rows = conn.execute(
        "SELECT mod_id, key, value, from_step, to_step FROM Mod_KV "
        "WHERE save_id = ? AND from_step <= ?;",
        (src_save_id, target_turn),
    ).fetchall()
    for mod_id, key, value, from_step, to_step in rows:
        clamped_to_step = None if (to_step is not None and to_step > target_turn) else to_step
        conn.execute(
            "INSERT INTO Mod_KV (save_id, mod_id, key, value, from_step, to_step) "
            "VALUES (?, ?, ?, ?, ?, ?);",
            (dst_save_id, mod_id, key, value, from_step, clamped_to_step),
        )


# ---------------------------------------------------------------------------
# Canonical Core Storage Registry
# ---------------------------------------------------------------------------
# Registry order matters for the fork: a table whose ids are referenced by a
# later one comes first (Facts -> Observations -> Mental_Models).

CORE_STORAGE_REGISTRY: list[TableStorageSpec] = [
    # Définition pure (non affectée par le rewind, copiée au fork)
    TableStorageSpec("Universe_Meta", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("key", "value")),
    TableStorageSpec("Entity_Types", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("type_id", "name", "role", "description", "is_builtin")),
    TableStorageSpec("Stat_Definitions", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("stat_id", "name", "description", "value_type", "parameters")),
    TableStorageSpec("Stat_Type_Links", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("stat_id", "type_id")),
    TableStorageSpec("Entities", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("entity_id", "entity_type", "entity_role", "name", "description", "is_active", "origin")),
    TableStorageSpec("Entity_Stats", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("entity_id", "stat_key", "stat_value")),
    TableStorageSpec("Rules", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("rule_id", "priority", "conditions", "actions", "target_entity")),
    TableStorageSpec("Lore_Book", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("entry_id", "category", "name", "keywords", "content")),
    TableStorageSpec("Locations", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("location_id", "name", "scale", "parent_id", "description", "x", "y")),
    TableStorageSpec("Location_Connections", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("source_id", "target_id", "distance_km")),
    TableStorageSpec("Scheduled_Events", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("event_id", "trigger_minute", "title", "description")),
    TableStorageSpec("Item_Definitions", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("item_id", "name", "description", "category", "weight", "rarity", "is_container", "capacity")),
    TableStorageSpec("Story_Setup", StoragePolicy.VERSIONED_KV, is_runtime=False,
                     columns=("setup_id", "question", "type", "options", "max_selections", "priority")),

    # Runtime / Sauvegarde (affecté par le rewind et le fork)
    # Schema versions of the mods' tables in THIS database: owned by the save db
    # (never copied from the universe, which may not have the mods' tables), not
    # per save_id, so neither forked, rewound nor purged.
    TableStorageSpec("Mod_Schema_Versions", StoragePolicy.VERSIONED_KV, is_runtime=True,
                     columns=("mod_id", "schema_version", "installed_at"), save_scoped=False),
    TableStorageSpec("Saves", StoragePolicy.VERSIONED_KV, is_runtime=True,
                     columns=("save_id", "player_name", "difficulty", "last_updated", "player_persona", "created_at")),
    TableStorageSpec("Event_Log", StoragePolicy.EVENTS, step_column="turn_id", is_runtime=True,
                     columns=("event_id", "save_id", "turn_id", "event_type", "target_entity", "payload"),
                     id_column="event_id", id_autoincrement=True),
    TableStorageSpec("State_Cache", StoragePolicy.DERIVED, step_column=None, is_runtime=True,
                     columns=("save_id", "entity_id", "stat_key", "stat_value")),
    TableStorageSpec("Snapshots", StoragePolicy.STEP_KEYED, step_column="turn_id", is_runtime=True,
                     columns=("save_id", "turn_id", "state_json")),
    TableStorageSpec("Session_Lore", StoragePolicy.STEP_KEYED, step_column="origin_turn", is_runtime=True,
                     columns=("entry_id", "save_id", "category", "name", "keywords", "content", "origin_turn"),
                     id_column="entry_id"),
    TableStorageSpec("Mod_KV", StoragePolicy.CUSTOM, is_runtime=True,
                     columns=("save_id", "mod_id", "key", "value", "from_step", "to_step"),
                     custom_rewind=_rewind_mod_kv, custom_fork=_fork_mod_kv),
]

_REGISTRY_LOCK = threading.RLock()

# The installed mods' storage is declared once per process before any rewind, fork,
# purge or copy — even when no modpack was loaded (CLI, tools, tests): a mod's data
# follows the save whether the mod is enabled or not (owner decision 2026-10-03).
_MOD_STORAGE_READY = False


def _ensure_mod_storage() -> None:
    global _MOD_STORAGE_READY
    if _MOD_STORAGE_READY:
        return
    _MOD_STORAGE_READY = True  # first: declaring reads the registry itself
    from axiom.kernel.loader import ensure_installed_storage_declared
    ensure_installed_storage_declared()


def mark_mod_storage_ready() -> None:
    """The installed mods' storage was just declared (by a modpack bootstrap)."""
    global _MOD_STORAGE_READY
    _MOD_STORAGE_READY = True


def reset_mod_storage() -> None:
    """Declare the installed mods' storage again at next use (tests, mods folder changed)."""
    global _MOD_STORAGE_READY
    _MOD_STORAGE_READY = False


# ---------------------------------------------------------------------------
# Public Helper Functions
# ---------------------------------------------------------------------------

def _specs() -> list[TableStorageSpec]:
    with _REGISTRY_LOCK:
        return list(CORE_STORAGE_REGISTRY)


def get_definition_tables() -> list[str]:
    """Return all universe definition table names."""
    return [spec.table_name for spec in _specs() if not spec.is_runtime]


def get_runtime_tables() -> list[str]:
    """Return the per-save SQL tables, ``Saves`` last (purge order: children first).

    External stores (vector memory, files) and per-database tables
    (``Mod_Schema_Versions``) are not save rows and are not listed.
    """
    _ensure_mod_storage()
    tables = [
        spec.table_name for spec in _specs()
        if spec.is_runtime and spec.save_scoped and not spec.external
    ]
    ordered = [t for t in reversed(tables) if t != "Saves"]
    if "Saves" in tables:
        ordered.append("Saves")
    return ordered


def get_definition_copy_specs() -> list[tuple[str, tuple[str, ...]]]:
    """Return (table_name, columns) pairs for copying universe definitions into a save db."""
    return [
        (spec.table_name, spec.columns)
        for spec in _specs()
        if not spec.is_runtime and spec.columns is not None
    ]


def get_runtime_copy_specs() -> list[tuple[str, tuple[str, ...]]]:
    """Return (table_name, columns) pairs for copying the per-save runtime rows."""
    _ensure_mod_storage()
    return [
        (spec.table_name, spec.columns)
        for spec in _specs()
        if spec.is_runtime and spec.save_scoped and not spec.external and spec.columns is not None
    ]


def _table_exists(conn: sqlite3.Connection, table: str) -> bool:
    # SQLite table names are case-insensitive: so is this check.
    return conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name = ? COLLATE NOCASE;", (table,)
    ).fetchone() is not None


def find_storage_spec(table_name: str) -> TableStorageSpec | None:
    """Registered spec of a table (case-insensitive, like SQLite), or None."""
    wanted = table_name.lower()
    for spec in _specs():
        if spec.table_name.lower() == wanted:
            return spec
    return None


def execute_rewind(
    conn: sqlite3.Connection,
    save_id: str,
    target_turn_id: int,
    *,
    external: bool = True,
) -> dict[str, int]:
    """Execute unified rewind on all registered SQL tables, on the caller's transaction.

    ``external=False`` leaves the non-SQL stores alone: the engine path
    (:meth:`axiom.checkpoint.CheckpointManager.rewind`) commits the SQL first,
    then calls :func:`execute_external_rewind`. ``external=True`` (default, kept
    for direct callers) runs them at the end of this call.
    """
    _ensure_mod_storage()
    from axiom.schema import (
        ensure_facts_table,
        ensure_fired_event_turn_column,
        ensure_inventory_snapshots_table,
        ensure_modifier_snapshots_table,
    )

    ensure_fired_event_turn_column(conn)
    ensure_facts_table(conn)
    ensure_modifier_snapshots_table(conn)
    ensure_inventory_snapshots_table(conn)

    deleted_count = 0
    specs = [s for s in _specs() if not s.external]

    # 1. EVENTS (Event_Log)
    for spec in specs:
        if spec.policy == StoragePolicy.EVENTS and _table_exists(conn, spec.table_name):
            cur = conn.execute(
                f"DELETE FROM {spec.table_name} WHERE save_id = ? AND {spec.step_column} > ?;",
                (save_id, target_turn_id),
            )
            deleted_count += cur.rowcount or 0

    # 2. STEP_KEYED tables (a table not created yet in an old db has nothing to rewind)
    for spec in specs:
        if spec.policy == StoragePolicy.STEP_KEYED and _table_exists(conn, spec.table_name):
            conn.execute(
                f"DELETE FROM {spec.table_name} WHERE save_id = ? AND {spec.step_column} > ?;",
                (save_id, target_turn_id),
            )

    # 3. CUSTOM handlers
    for spec in specs:
        if spec.policy == StoragePolicy.CUSTOM and spec.custom_rewind is not None:
            spec.custom_rewind(conn, save_id, target_turn_id)

    if external:
        execute_external_rewind(save_id, target_turn_id)

    return {"deleted_events": deleted_count, "rebuilt_to_turn": target_turn_id}


def get_state_sections() -> list[TableStorageSpec]:
    """Storages exposing a save-editor section (registry order)."""
    _ensure_mod_storage()
    return [spec for spec in _specs() if spec.section]


def execute_snapshots(conn: sqlite3.Connection, save_id: str, turn_id: int) -> None:
    """End-of-turn captures of the registered storages, on the turn's transaction."""
    _ensure_mod_storage()
    for spec in _specs():
        if spec.custom_snapshot is not None and not spec.external:
            spec.custom_snapshot(conn, save_id, turn_id)


def execute_external_rewind(save_id: str, target_turn_id: int) -> list[str]:
    """Rewind the external (non-SQL) stores. Call it AFTER the SQL rewind is committed.

    A failing store does not stop the others; it is logged and its name returned
    (the SQL state is already committed and stays the source of truth).
    """
    _ensure_mod_storage()
    failed: list[str] = []
    for spec in _specs():
        if spec.external and spec.custom_rewind is not None:
            try:
                spec.custom_rewind(None, save_id, target_turn_id)
            except Exception:
                logger.exception(
                    "External storage '%s' (mod %s) failed to rewind save %s to turn %d",
                    spec.table_name, spec.owner, save_id, target_turn_id,
                )
                failed.append(spec.table_name)
    return failed


def _fork_generic(
    conn: sqlite3.Connection,
    spec: TableStorageSpec,
    src_save_id: str,
    dst_save_id: str,
    at_turn: int,
) -> dict[Any, Any]:
    """Copy the rows ``step_column <= at_turn`` of a step-keyed table from its
    declared columns. Returns the {old_id: new_id} mapping (empty without id_column)."""
    if spec.columns is None or spec.step_column is None:
        raise ValueError(f"Step-keyed table '{spec.table_name}' needs columns and a step_column.")
    data_cols = [c for c in spec.columns if c not in ("save_id", spec.id_column)]
    select_cols = ([spec.id_column] if spec.id_column else []) + data_cols
    order = f" ORDER BY {spec.id_column}" if spec.id_autoincrement else ""
    rows = conn.execute(
        f"SELECT {', '.join(select_cols)} FROM {spec.table_name} "
        f"WHERE save_id = ? AND {spec.step_column} <= ?{order};",
        (src_save_id, at_turn),
    ).fetchall()

    id_map: dict[Any, Any] = {}
    insert_cols = ["save_id"] + data_cols
    if spec.id_column and not spec.id_autoincrement:
        insert_cols = [spec.id_column] + insert_cols
    sql = (
        f"INSERT INTO {spec.table_name} ({', '.join(insert_cols)}) "
        f"VALUES ({', '.join('?' * len(insert_cols))});"
    )
    for row in rows:
        values = list(row)
        old_id = values.pop(0) if spec.id_column else None
        params = [dst_save_id] + values
        if spec.id_column and not spec.id_autoincrement:
            new_id: Any = str(uuid.uuid4())
            params = [new_id] + params
            conn.execute(sql, params)
        else:
            new_id = conn.execute(sql, params).lastrowid
        if spec.id_column:
            id_map[old_id] = new_id
    return id_map


def execute_fork(
    conn: sqlite3.Connection,
    src_save_id: str,
    dst_save_id: str,
    at_turn: int,
    *,
    external: bool = True,
) -> dict[str, dict[Any, Any]]:
    """Copy all registered runtime tables from src_save_id up to at_turn into dst_save_id.

    Generic for EVENTS / STEP_KEYED tables (declared columns, ids regenerated);
    CUSTOM tables use their handler. Errors propagate: a fork never silently
    drops data. Returns the id mappings {table: {old_id: new_id}}.
    ``external=False``: the caller runs :func:`execute_external_fork` after its commit.
    """
    _ensure_mod_storage()
    from axiom.schema import (
        ensure_facts_table,
        ensure_fired_event_turn_column,
        ensure_inventory_snapshots_table,
        ensure_modifier_snapshots_table,
    )
    ensure_fired_event_turn_column(conn)
    ensure_facts_table(conn)
    ensure_modifier_snapshots_table(conn)
    ensure_inventory_snapshots_table(conn)

    id_maps: dict[str, dict[Any, Any]] = {}
    for spec in _specs():
        if not spec.is_runtime or not spec.save_scoped or spec.external or spec.fork_with:
            continue
        if spec.custom_fork is not None:
            # Handlers receive the id mappings of the tables forked before them
            # (registry order = declaration order).
            spec.custom_fork(conn, src_save_id, dst_save_id, at_turn, id_maps=id_maps)
        elif spec.policy in (StoragePolicy.EVENTS, StoragePolicy.STEP_KEYED):
            if _table_exists(conn, spec.table_name):
                id_maps[spec.table_name] = _fork_generic(conn, spec, src_save_id, dst_save_id, at_turn)

    if external:
        execute_external_fork(src_save_id, dst_save_id, at_turn)
    return id_maps


def execute_external_fork(src_save_id: str, dst_save_id: str, at_turn: int) -> list[str]:
    """Fork the external (non-SQL) stores. Call it AFTER the SQL fork is committed."""
    _ensure_mod_storage()
    failed: list[str] = []
    for spec in _specs():
        if spec.external and spec.custom_fork is not None:
            try:
                spec.custom_fork(None, src_save_id, dst_save_id, at_turn)
            except Exception:
                logger.exception(
                    "External storage '%s' (mod %s) failed to fork save %s at turn %d",
                    spec.table_name, spec.owner, src_save_id, at_turn,
                )
                failed.append(spec.table_name)
    return failed


# Specs replaced by a newer registration of the same name, restored when the newer
# one is unregistered (a mod loaded twice, e.g. a second modpack in tests).
_SHADOWED: dict[int, TableStorageSpec] = {}


def register_table_storage(spec: TableStorageSpec) -> TableStorageSpec | None:
    """Register or replace a table storage specification. Returns the replaced spec
    (put back when ``spec`` is unregistered)."""
    with _REGISTRY_LOCK:
        for i, s in enumerate(CORE_STORAGE_REGISTRY):
            if s.table_name.lower() == spec.table_name.lower():
                CORE_STORAGE_REGISTRY[i] = spec
                _SHADOWED[id(spec)] = s
                return s
        CORE_STORAGE_REGISTRY.append(spec)
        return None


def register_custom_storage(
    table_name: str,
    rewind_callback: Callable[[sqlite3.Connection | None, str, int], None] | None = None,
    fork_callback: Callable[[sqlite3.Connection | None, str, str, int], None] | None = None,
    *,
    owner: str | None = None,
) -> TableStorageSpec:
    """Register an external (non-SQL) store: vector DB, generated files...

    Its callbacks run after the SQL rewind/fork is committed and receive
    ``conn=None``. Mods should go through ``ModContext.register_storage`` so the
    registration is removed when the mod is disabled (D11).
    """
    spec = TableStorageSpec(
        table_name=table_name,
        policy=StoragePolicy.CUSTOM,
        step_column=None,
        is_runtime=True,
        custom_rewind=rewind_callback,
        custom_fork=fork_callback,
        save_scoped=False,
        external=True,
        owner=owner,
    )
    register_table_storage(spec)
    return spec


def unregister_storage(spec: TableStorageSpec) -> bool:
    """Remove exactly this registration (a newer one with the same name is kept);
    the registration it had replaced, if any, comes back."""
    with _REGISTRY_LOCK:
        previous = _SHADOWED.pop(id(spec), None)
        for i, s in enumerate(CORE_STORAGE_REGISTRY):
            if s is spec:
                if previous is not None:
                    CORE_STORAGE_REGISTRY[i] = previous
                else:
                    del CORE_STORAGE_REGISTRY[i]
                return True
        # Already replaced by a newer one: that newer one must restore `previous`.
        if previous is not None:
            for key, shadowed in list(_SHADOWED.items()):
                if shadowed is spec:
                    _SHADOWED[key] = previous
    return False


# ---------------------------------------------------------------------------
# Mod schema migrations (per save database)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ModMigrations:
    mod_id: str
    target_version: int
    migrations: dict[int, Callable[[sqlite3.Connection], None]]


_MOD_MIGRATIONS: dict[str, ModMigrations] = {}


def register_mod_migrations(
    mod_id: str,
    target_version: int,
    migrations: dict[int, Callable[[sqlite3.Connection], None]],
) -> ModMigrations:
    """Declare a mod's table migrations (version N -> N+1 callables).

    They are applied to every save database the engine opens or creates
    (:func:`apply_registered_mod_migrations`), tracked in ``Mod_Schema_Versions``.
    """
    entry = ModMigrations(mod_id, int(target_version), dict(migrations))
    with _REGISTRY_LOCK:
        _MOD_MIGRATIONS[mod_id] = entry
    return entry


def unregister_mod_migrations(entry: ModMigrations) -> None:
    with _REGISTRY_LOCK:
        if _MOD_MIGRATIONS.get(entry.mod_id) is entry:
            del _MOD_MIGRATIONS[entry.mod_id]


def get_registered_mod_migrations() -> list[ModMigrations]:
    with _REGISTRY_LOCK:
        return list(_MOD_MIGRATIONS.values())


def apply_registered_mod_migrations(db_path: str) -> list[str]:
    """Bring the mods' tables of ``db_path`` to their declared versions.

    A failing migration raises (its own transaction is rolled back): the save
    must not be played with a half-migrated mod schema. Returns the mod ids processed.
    """
    from axiom.schema import apply_mod_migrations

    done: list[str] = []
    for entry in get_registered_mod_migrations():
        apply_mod_migrations(str(db_path), entry.mod_id, entry.target_version, entry.migrations)
        done.append(entry.mod_id)
    return done
